### ISSUE TITLE
Log errors and warnings

### ISSUE THREAD

**Issue by spuljko** [kpisacic/DHMZ-home-assistant-custom-component#11]
There are few errors and warnings in log file:
Logger: homeassistant.components.weather
Source: custom_components/dhmz/weather.py:182
Integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 11:34:33 AM (2 occurrences)
Last logged: 11:34:33 AM

1.
Error adding entities for domain weather with platform dhmz
Error while setting up dhmz platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/dhmz/weather.py", line 182, in extra_state_attributes
    "pressure_tendency": self.dhmz_data.get_data(SENSOR_TYPES["pressure_tendency"][4]) + " hPa",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

2.
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: 11:34:29 AM (2 occurrences)
Last logged: 11:34:29 AM

custom_components.dhmz.weather::DhmzWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.
custom_components.eko_karta_zagreb.weather::EkoKartaZagrebWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.

3.
Logger: custom_components.dhmz.weather
Source: custom_components/dhmz/weather.py:123
Integration: dhmz
First occurred: 11:34:30 AM (1 occurrences)
Last logged: 11:34:30 AM

Unknown DHMZ weather symbol: None

4. (also for other sensors - wind, pressure etc)
Logger: custom_components.dhmz.weather
Source: custom_components/dhmz/weather.py:223
Integration: dhmz
First occurred: 11:34:33 AM (1 occurrences)
Last logged: 11:34:33 AM

Humidity - value not float:

**Comment by kpisacic** [comment]
Number 2 is resolved in https://github.com/kpisacic/DHMZ-home-assistant-custom-component/commit/8318966ba9558cbbc470a2567a7db889e466e15b , and i believe others are just consequence of using old deprecated methods, or actual wrong data coming from the DHMZ service (which is sometimes encountered).
