### ISSUE TITLE
Weather Card

### ISSUE THREAD

**Issue by Notrial** [kpisacic/DHMZ-home-assistant-custom-component#13]
Čini se da je weather card depricated sa novom verzijom Home Assistanta?

![image](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/17e1fb2e-5efb-447e-8779-55aa7d46ff68)

**Comment by kpisacic** [comment]
Pozdrav, nova verzija je commitana prije nekih mjesec dana, u ovome repozitoriju i u https://github.com/kpisacic/lovelace-dhmz-weather-card . Razlika u ovome drugome je samo u tome da je struktura direktorija prilagođena da je automatski hendla HACS. Ali same verzije .js fajla su iste.
Više nije Javascript File, već je sada modul. U prilogu je sadašnje stanje.
![Screenshot_20230627_200120_Chrome](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/55980860/f0b06b7c-fcdf-4872-a0a0-bc55f42f92e7)

**Comment by Notrial** [comment]
Ovo radi! Ja sam imao još mimo HACS-a instaliranu karticu...ovako je bolje svakako!

Hvala!

**Comment by Notrial** [comment]
Nakon updejta na predzadnju verziju Hass-a, čini se da ne prikazuje cijelu karticu (samo ikone sunca/oblaka itd).
![image](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/7fbd2f52-e54f-4960-83d1-bac99a61e6b3)

**Comment by kpisacic** [comment]
Proučavam... povećao se ChartJS na V4, pa ima dosta promjena. Javim kada pofixam.

**Comment by kpisacic** [comment]
Bok, fixano je u zadnjem commitu, i na ovom ( https://github.com/kpisacic/DHMZ-home-assistant-custom-component/commit/181049f08472ebecfde62396ece6f7be9c203bbc ) i na repozirotiju za HACS componentu ( https://github.com/kpisacic/lovelace-dhmz-weather-card/commit/ea518e0fe65351bd16a28ce55f2749a6e6062611 repozirotiju )
Sada bi trebalo raditi, iako jos ima otvorenih warninga za deprication FORECAST atributa, ali to ce jos raditi par mjeseci, a u medjuvremenu cu to prepraviti.

**Comment by Notrial** [comment]
Sve radi! Thanks!
