### ISSUE TITLE
Card stopped working after recent update

### ISSUE THREAD

**Issue by Notrial** [kpisacic/DHMZ-home-assistant-custom-component#14]
Can you please check if it still works for you?

**Comment by crnah2o** [comment]
![slika](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/80674686/72b41371-8b7a-4308-ac54-b3749648efef)


Working for me just fine (I guess)... Are you using the one that came with this "custom component", or the one from it's own repo? I'm not sure any more, but I think the one from its own repo is outdated and you should use the one that you downloaded from this repo (with the custom component).

**Comment by Notrial** [comment]
I'm using this one AFAIK.
Weather component works fine as you can see:

<img width="1443" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/59cb09bb-40bf-4995-a07b-ee1b0391aa96">

And frontend one is installed via HACS:
<img width="543" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/9e32a74c-ef1d-44a2-a087-3266b6e6c313">
<img width="625" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/62c810a0-a346-4f4b-883f-5e1b1aca3895">

But it is not rendering in the UI at all:
<img width="649" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/c7bf8aa4-d9b4-48e0-8d1d-a844e9b74084">

Should be here above the Windy map:
![image](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/82df661a-7851-4040-a001-da26a880b0ed)

**Comment by kpisacic** [comment]
Both are identical files dhmz-weather-card.js (minus some logging which is commented out). If you use lovelace version it should install automatically. If you use version in this repository when you need to install it (copy) manually. 
For me it is working, even do i am still on 2024.03.03 release of HA. I did not still upgrade to 2024.04.* . Which version are you running? 
I see some deprecated changes, maybe they are affecting it. If it is problem with 2024.04.* can only debug this in a few day, i am pretty much overbooked now.

**Comment by Notrial** [comment]
Yep, I'm on the latest one. That is most likely it. Let me know once you get some time to tackle it please.

Thanks!

**Comment by kpisacic** [comment]
Check last update, to both service (this repository) and card (another repository or file in this one).
It is quick fix, to amend to changes in forecast services - it was not done to use service, but to workaround it. i will re-work whole service when i will have more time. 
But i did upgrade to 2024.4.3 on my installations (dev and working) and it works fine now. Please check.

**Comment by Notrial** [comment]
I've updated both and restarted, now at least it shows an error :)

<img width="530" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/360a978c-7f20-474c-a3d5-ae6e9c5e4b87">

Not sure what is going on, I checked file location, it is also added as a resource in resources.yaml.
Scratching my head over here.

**Comment by kpisacic** [comment]
Hm, strange if it was working before.
Please check in Edit Dashboard -> Manage resources if HACS has created resource.
If it is, check in debug console ( F12 or development tools in Chrome) what error is displayed in console window.

**Comment by Notrial** [comment]
I just realised that it works on mobile app, so it must be some caching issue on desktop I guess.
Another quick question though. My card looks a bit different than yours above (not talking about dark/light theme).
Any clues there?


![DA1E9956-A1F7-4403-B029-9E5F0473FA30_4_5005_c](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/063fbb7e-4db0-4abd-b0b1-a8f29b795981)

**Comment by kpisacic** [comment]
This is how it should look.
![Screenshot_20240421_162940_Chrome](https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/55980860/3489a9cd-80a3-46bc-922c-3e122eab9fe6)

**Comment by Notrial** [comment]
OK, cool. Then it is fine :)

Thanks again, I still have to figure out the issue with desktop Chrome.

<img width="563" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/a00c33f6-60f6-400b-a166-d0425f83d200">

FYI works in Safari as well...just tested.

Cheers!

**Comment by Notrial** [comment]
Just wanted to make sure you saw my edit in the message above. Card is not working in Chrome, but it does work in Safari for example, so it must be something in JS file that is causing this (console error log above). Any clues?

**Comment by kpisacic** [comment]
No, did not see it sorry. In this line of code, change happend with new version. Split is done of forecast_list attribute, which is newly added into attributes section. Working in Safari and not in Chrome, on same HA instance is only possible if Chrome did not refresh dhms-weather-card.js file. Because, previously in this line it was "forecast" attribute, which does not exist any more in HA.
In the console log above, click on this link "dhms-weather-card.js:91:60" and it will open JS file. Check content of this line 91. If it is not:

`var tmp_forecast = this.weatherObj.attributes.forecast_list.slice(0,29);`

then you are still using old version of JS file. Try right-clicking file in new tab and there click Ctrl-F5 or Shift-F5 - to force refresh JS.

**Comment by Notrial** [comment]
<img width="703" alt="image" src="https://github.com/kpisacic/DHMZ-home-assistant-custom-component/assets/36201754/1ee280f8-f95d-4cc8-a108-cbbb367e3d82">

Damn Chrome...like you said I had to open JS file itself in a separate Chrome tab and force refresh it. Refreshing Hass tab in any way didn't change anything.

Thanks a lot for your help, really appreciate your work on this integration!
