### ISSUE TITLE
Type Error - Undefined

### ISSUE THREAD

**Issue by bebach8** [kpisacic/DHMZ-home-assistant-custom-component#3]
Home assistant version 0.113 - 0.115

Logger: frontend.js.latest.202009171
Source: components/system_log/__init__.py:193
First occurred: 11:37:33 AM (242 occurrences)
Last logged: 11:40:53 AM

    https://xxx.xxx.xxx.xxx:8123/local/dhmz-weather-card.js:248:47 Uncaught TypeError: Cannot read property 'forecast' of undefined
    https://xxx.xxx.xxx.xxx:8123/local/dhmz-weather-card.js:248:20 TypeError: this.weatherObj.attributes is undefined
    https://xxx.xxx.xxx.xxx:8123/frontend_latest/chunk.d9cbf2fe4e32a009641f.js:2:69001 TypeError: s._view is undefined
    https://xxx.xxx.xxx.xxx:8123/local/dhmz-weather-card.js:248:18 TypeError: this.weatherObj.attributes is undefined

**Comment by bebach8** [comment]
Breaking change in 0.115 

[https://github.com/home-assistant/frontend/pull/6671]

After changing `<ha-chart-base` `data="[[ChartData]]"></ha-chart-base>`
to `<ha-chart-base` hass="[[_hass]]" `data="[[ChartData]]"></ha-chart-base>`
graph works again.

Could you please fix it in repo?

Hvala :-)

**Comment by kpisacic** [comment]
change in last commit. Thank you!
