### ISSUE TITLE
update to python 3.9

### ISSUE THREAD

**Issue by markokristof** [kpisacic/DHMZ-home-assistant-custom-component#5]
Active graph is broken, seems that discontinued support for python 3.7 is the issue.

**Comment by kpisacic** [comment]
I have upgrade on my production RasPI3 with HassIO to 2021.2.0, it left python 3.8.5 - and graph (of DHMZ temperatures) is still working.
I have upgrade my dev setup to DEV branch and python 3.9 - and graph is still working.
Please be precise what issue do you see, and what error led you to believe python3.9 is to blame?

**Comment by markokristof** [comment]
Now it works. It did not work yesterday after the  HA update that dropped the python 3.7 support. I assumed that python is to blame.
