### ISSUE TITLE
Weather Card - meteogram vise ne radi

### ISSUE THREAD

**Issue by Notrial** [kpisacic/DHMZ-home-assistant-custom-component#7]
Ne znam jel samo do mene ali mi kartica ne prikazuje meteogram (mislim unazad mjesec dana). Sve ostalo je ok…screenshot u privitku.

![55B664D0-899B-4B97-AC9B-F8D846D26790](https://user-images.githubusercontent.com/36201754/132105727-32d440d5-ccab-40bd-9ef4-d7f938b1ce8c.png)

**Comment by kpisacic** [comment]
Jesi li probao uzeti zadnji www/dhmz-weather-card.js tu sa git-a. Prije nekih 2 mjeseca sam radio update koji je bio za verziju 2021.07+ a gdje je problem bio upravo taj da se nije vidio graf.
Please probaj sa tom verzijom, i nakon što stavis nivi fajl obrisi cache u browseru (inace tesko povlači novu verziju).

**Comment by Notrial** [comment]
Da, to je bilo to, sada radi!

Hvala!
