### ISSUE TITLE
Warning in log file

### ISSUE THREAD

**Issue by spuljko** [kpisacic/DHMZ-home-assistant-custom-component#9]
Entity sensor.dhmz_sensor_maksimir_forecast_text_today (<class 'custom_components.dhmz.sensor.DhmzSensor'>) implements device_state_attributes. Please report it to the custom component author

Rename the property device_state_attributes to extra_state_attributes
https://developers.home-assistant.io/docs/core/entity?_highlight=extra_state_attributes#generic-properties

**Comment by kpisacic** [comment]
Fixed in commit - 621fd4c78d06e60517611d30daa0af851666f5e1
